name: Build & Publish App

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: home-assistant/builder@master
        with:
          args: >-
            --dir ./mcpo
