name: Build app image

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
      publish:
        required: true
        type: boolean

jobs:
  build:
    name: Build ${{ inputs.app }}
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out repository
        uses: actions/checkout@v4

      - name: 🚀 Build mcpo app image
        uses: home-assistant/builder@master
        with:
          args: >-
            --test
            --dir ./mcpo
            --compress zstd
            --addons-url https://github.com/TheSpaceGod/mcpo-hass-app
            --target /tmp/mcpo
          publish: ${{ inputs.publish }}
